- filename: "/products/x4012.html"
  data:
    name: X4012两节导轨
    title: X4012两节导轨
    keywords: X4012两节导轨
    description: X4012两节导轨
    filter:
      - 家具五金
      - 小区
      - 洋房
      - 别墅
      - 宾馆
      - 商业地铺
      - 办公楼
      - 现代简约
      - 冷轧刚
    images:
      - x4012.jpg
    recommendations:
      - X4012两节导轨
  content: |
    <div class="product">
      <h1>门锁系列XC270-52</h1>
      <p>描述文字</p>
    </div>

- filename: "/products/x4605.html"
  data:
    name: X4605三节导轨
    title: X4605三节导轨
    keywords: X4605三节导轨
    description: X4605三节导轨
    filter:
      - 家具五金
      - 小区
      - 洋房
      - 别墅
      - 宾馆
      - 商业地铺
      - 办公楼
      - 现代简约
      - 冷轧刚
    images:
      - x4605.jpg
    recommendations:
      - X4605三节导轨
  content: |
    <div class="product">
      <h1>门锁系列XC270-52</h1>
      <p>描述文字</p>
    </div>


- filename: "/products/x5430ab.html"
  data:
    name: X5430AB青古铜合页
    title: X5430AB青古铜合页
    keywords: X5430AB青古铜合页
    description: X5430AB青古铜合页
    filter:
      - 家具五金
      - 小区
      - 洋房
      - 别墅
      - 中式仿古
      - 不锈钢
    images:
      - x5430.jpg
    recommendations:
      - X5430AB青古铜合页
  content: |
    <div class="product">
      <h1>门锁系列XC270-52</h1>
      <p>描述文字</p>
    </div>