- filename: "/products/XC270-52/index.html"
  data:
    name: 门锁系列XC270-52
    title: 门锁系列XC270-52
    keywords: 门锁系列XC270-52
    description: 门锁系列XC270-52
    filter:
      - 类型2
      - 颜色1
    images:
      - XC270-52.jpg
  content: |
    <div class="product">
      <h1>门锁系列XC270-52</h1>
      <p>描述文字</p>
    </div>

- filename: "/products/XY256-55G/index.html"
  data:
    name: 门锁系列XY256-55G
    title: 门锁系列XY256-55G
    keywords: 门锁系列XY256-55G
    description: 门锁系列XY256-55G
    filter:
      - 类型1
      - 颜色2
    images:
      - XY256-55G.jpg
  content: |
    <div class="product">
      <h1>门锁系列XY256-55G</h1>
      <p>描述文字</p>
    </div>
